language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4.2'
  - '5.0'
  - '6.0'

sudo: false

script: "npm run-script test-ci"

after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
