language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '4.3'
  - '4.4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'

sudo: false

script: "npm run-script test-ci"

after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
